{"variants":[{"paths":["\/documentation\/swiftkyber\/exception\/asn1structure"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Wrong ASN1 structure"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asn1Structure"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"SwiftKyber"}],"externalID":"s:10SwiftKyber9ExceptionO13asn1StructureyA2CmF","title":"Exception.asn1Structure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asn1Structure"}],"role":"symbol","symbolKind":"case"},"identifier":{"url":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/asn1Structure","interfaceLanguage":"swift"},"references":{"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception/asn1Structure":{"role":"symbol","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/asn1Structure","kind":"symbol","type":"topic","title":"Exception.asn1Structure","url":"\/documentation\/swiftkyber\/exception\/asn1structure","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asn1Structure"}],"abstract":[{"text":"Wrong ASN1 structure","type":"text"}]},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber":{"abstract":[{"type":"text","text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard"}],"kind":"symbol","type":"topic","role":"collection","title":"SwiftKyber","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","url":"\/documentation\/swiftkyber"},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception":{"type":"topic","abstract":[{"text":"The Kyber exceptions","type":"text"}],"kind":"symbol","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Exception"}],"url":"\/documentation\/swiftkyber\/exception","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Exception"}],"title":"Exception"}}}