{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/swiftkyber\/exception\/ciphertextsize(value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","roleHeading":"Case","externalID":"s:10SwiftKyber9ExceptionO14cipherTextSizeyACSi_tcACmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cipherTextSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"Exception.cipherTextSize(value:)","modules":[{"name":"SwiftKyber"}],"symbolKind":"case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"identifier":{"url":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/cipherTextSize(value:)","interfaceLanguage":"swift"},"abstract":[{"text":"Wrong cipher text size","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cipherTextSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","references":{"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/swiftkyber","title":"SwiftKyber","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","abstract":[{"type":"text","text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard"}]},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception":{"navigatorTitle":[{"text":"Exception","kind":"identifier"}],"identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception","role":"symbol","title":"Exception","type":"topic","url":"\/documentation\/swiftkyber\/exception","kind":"symbol","abstract":[{"text":"The Kyber exceptions","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Exception","kind":"identifier"}]},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception/cipherTextSize(value:)":{"abstract":[{"text":"Wrong cipher text size","type":"text"}],"url":"\/documentation\/swiftkyber\/exception\/ciphertextsize(value:)","kind":"symbol","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/cipherTextSize(value:)","role":"symbol","title":"Exception.cipherTextSize(value:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cipherTextSize","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"}}}