{"metadata":{"roleHeading":"API Collection","modules":[{"name":"SwiftKyber"}],"title":"Error Implementations","role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/localizedDescription"]}],"identifier":{"url":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/Error-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"paths":["\/documentation\/swiftkyber\/exception\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception":{"navigatorTitle":[{"text":"Exception","kind":"identifier"}],"identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception","role":"symbol","title":"Exception","type":"topic","url":"\/documentation\/swiftkyber\/exception","kind":"symbol","abstract":[{"text":"The Kyber exceptions","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Exception","kind":"identifier"}]},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/swiftkyber","title":"SwiftKyber","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","abstract":[{"type":"text","text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard"}]},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception/localizedDescription":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/localizedDescription","title":"localizedDescription","url":"\/documentation\/swiftkyber\/exception\/localizeddescription"}}}