{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pemStructure","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Wrong PEM structure","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftkyber\/exception\/pemstructure"]}],"kind":"symbol","metadata":{"title":"Exception.pemStructure","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pemStructure","kind":"identifier"}],"externalID":"s:10SwiftKyber9ExceptionO12pemStructureyA2CmF","modules":[{"name":"SwiftKyber"}],"roleHeading":"Case","symbolKind":"case","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/pemStructure"},"references":{"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber":{"title":"SwiftKyber","url":"\/documentation\/swiftkyber","kind":"symbol","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber","type":"topic","abstract":[{"text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard","type":"text"}],"role":"collection"},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception/pemStructure":{"identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception\/pemStructure","url":"\/documentation\/swiftkyber\/exception\/pemstructure","type":"topic","title":"Exception.pemStructure","role":"symbol","abstract":[{"type":"text","text":"Wrong PEM structure"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pemStructure","kind":"identifier"}]},"doc://swiftkyber.SwiftKyber/documentation/SwiftKyber/Exception":{"role":"symbol","title":"Exception","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The Kyber exceptions"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Exception","kind":"identifier"}],"url":"\/documentation\/swiftkyber\/exception","identifier":"doc:\/\/swiftkyber.SwiftKyber\/documentation\/SwiftKyber\/Exception","navigatorTitle":[{"text":"Exception","kind":"identifier"}]}}}