{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encapsulationKeyInconsistent","kind":"identifier"}],"platforms":["macOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception\/encapsulationKeyInconsistent"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftkyber\/exception\/encapsulationkeyinconsistent"]}],"metadata":{"externalID":"s:10SwiftKyber9ExceptionO28encapsulationKeyInconsistentyA2CmF","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"SwiftKyber"}],"title":"Exception.encapsulationKeyInconsistent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encapsulationKeyInconsistent"}]},"abstract":[{"text":"Inconsistent encapsulation key data","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftKyber\/documentation\/SwiftKyber","doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"references":{"doc://SwiftKyber/documentation/SwiftKyber":{"title":"SwiftKyber","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/swiftkyber","abstract":[{"text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard","type":"text"}]},"doc://SwiftKyber/documentation/SwiftKyber/Exception/encapsulationKeyInconsistent":{"kind":"symbol","url":"\/documentation\/swiftkyber\/exception\/encapsulationkeyinconsistent","title":"Exception.encapsulationKeyInconsistent","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception\/encapsulationKeyInconsistent","abstract":[{"text":"Inconsistent encapsulation key data","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encapsulationKeyInconsistent"}],"type":"topic"},"doc://SwiftKyber/documentation/SwiftKyber/Exception":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exception"}],"type":"topic","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception","role":"symbol","title":"Exception","url":"\/documentation\/swiftkyber\/exception","abstract":[{"text":"The Kyber exceptions","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Exception"}]}}}