{"metadata":{"roleHeading":"Case","modules":[{"name":"SwiftKyber"}],"role":"symbol","symbolKind":"case","externalID":"s:10SwiftKyber9ExceptionO28encapsulationKeyInconsistentyA2CmF","title":"Exception.encapsulationKeyInconsistent","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encapsulationKeyInconsistent"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception\/encapsulationKeyInconsistent"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encapsulationKeyInconsistent","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/swiftkyber\/exception\/encapsulationkeyinconsistent"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"type":"text","text":"Inconsistent encapsulation key data"}],"hierarchy":{"paths":[["doc:\/\/SwiftKyber\/documentation\/SwiftKyber","doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"references":{"doc://SwiftKyber/documentation/SwiftKyber/Exception/encapsulationKeyInconsistent":{"identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception\/encapsulationKeyInconsistent","type":"topic","title":"Exception.encapsulationKeyInconsistent","kind":"symbol","abstract":[{"type":"text","text":"Inconsistent encapsulation key data"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"encapsulationKeyInconsistent","kind":"identifier"}],"url":"\/documentation\/swiftkyber\/exception\/encapsulationkeyinconsistent","role":"symbol"},"doc://SwiftKyber/documentation/SwiftKyber":{"url":"\/documentation\/swiftkyber","abstract":[{"text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard","type":"text"}],"title":"SwiftKyber","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber"},"doc://SwiftKyber/documentation/SwiftKyber/Exception":{"type":"topic","url":"\/documentation\/swiftkyber\/exception","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Exception","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Exception"}],"title":"Exception","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception","abstract":[{"type":"text","text":"The Kyber exceptions"}]}}}